name: Windows Test

on:
workflow_dispatch:

jobs:
test:
runs-on: windows-2022

```
steps:
  - name: Test Windows
    shell: pwsh
    run: |
      Write-Host "Windows runner OK"
      Write-Host "Runner: $env:RUNNER_NAME"
      Write-Host "OS: $env:RUNNER_OS"
      Write-Host "Architecture: $env:RUNNER_ARCH"
```
